name: Copy files

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure GCP credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.TEST_GCP_CREDENTIALS }}
      
      - name: Copy to GCP Storage Bucket
        run: |
          gsutil cp *.txt gs://sqb-bucket
          gsutil cp -r ./dist/ gs://sqb-bucket